### ISSUE TITLE
Get deals summary from HubSpot and create a txt file

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/engine-sales#7]
Get deals summary from HubSpot and output a list of txt by deals
Option: anonymize personal data

**Comment by FlorentLvr** [comment]
Input
- pipeline_id
- dealstage_id
- activities

Model
- list deals
- get activities from deals

Output
- create txt summary output per deal stored in outputs/deals/deal_id_deal_name

**Comment by FlorentLvr** [comment]
To be done in abi repo
